name: pim
description: Personal information manager

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  scoped_model: ^2.0.0
  sqflite: ^2.1.0+1
  path_provider: ^2.0.11
  flutter_slidable: ^2.0.0
  intl: ^0.17.0
  image_picker: ^0.8.6
  flutter_calendar_carousel: ^2.4.0
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
